### ISSUE TITLE
Empty page?!

### ISSUE THREAD

**Issue by kelson42** [openzim/mindtouch#114]
![Image](https://github.com/user-attachments/assets/381c5b78-eedf-4ba7-b313-ed4208214a40)

Not sure this is normal.

**Comment by benoit74** [comment]
Same page as online, not a scraper bug.

Note that for next bug reports, please:
- compare with online pages and report only if there is a difference with online ; there are tons of weird pages across all libretexts.org, I can't spend my time double checking this, it is easy to compare with online with the button in the upper right corner
- provide the link: I'm speaking about the full link, not the one without fragment because it is hidden by kiwix-serve viewer ; e.g. https://demo.library.kiwix.org/content/libretexts.org_en_phys/index.html#/Courses/Fresno_City_College here
- or steps to reproduce

**Comment by kelson42** [comment]
@benoit74 We should ideally put a long to the original page: the combination of "we mirror shit if there shit upstream" and "there is no straight way forward to check upstream source"... is kind of the best way to stop making bug reports.

EDIT: I just discovered the small logo in the top right corner :) My bad.
